# Generated by Django 3.1.1 on 2020-09-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Choice_A', models.CharField(max_length=200)),
                ('Choice_B', models.CharField(max_length=200)),
                ('Choice_C', models.CharField(max_length=200)),
                ('Choice_D', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
    ]
