# Generated by Django 3.1.1 on 2020-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
