# Generated by Django 3.1.1 on 2020-09-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200915_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
