# Generated by Django 3.1.1 on 2020-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionchoice'),
        ),
    ]
