# Generated by Django 3.1.1 on 2020-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200915_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
